const colors = require('tailwindcss/colors');
module.exports = {
	purge: ['./src/**/*.{html,js}'],
	darkMode: false, // or 'media' or 'class'
	theme: {
		extend: {
			fontFamily: {
				mont: 'Montserrat, ui-sans-serif, sans-serif',
				// crete: 'Crete Round, ui-sans-serif, sans-serif',
				// sig: 'Signika, ui-sans-serif, sans-serif',
				// vare: 'Varela Round',
				// cabin: 'Cabin',
			},
		},
		colors: {
			transparent: 'transparent',
			black: colors.black,
			white: colors.white,
			gray: colors.blueGray,
			green: colors.green,
			lblue: colors.lightBlue,
			yellow: colors.yellow,
			textbase: 'var(--text)',
			textstrong: 'var(--textstrong)',
			textweak: 'var(--textweak)',
			header: 'var(--header)',
			subheader: 'var(--subheader)',
			cardbase: 'var(--cardbase)',
			cardhover: 'var(--cardhover)',
			cardborder: 'var(--cardborder)',
			columnheader: 'var(--columnheader)',
			columnheadertext: 'var(--columnheadertext)',
			link: 'var(--link)',
			linkhover: 'var(--linkhover)',
			navtext: 'var(--navtext)',
			navicon: 'var(--navicon)',
			navhover: 'var(--navhover)',
			navcurrent: 'var(--navcurrent)',
			tabbase: 'var(--tab)',
			tabhover: 'var(--tabhover)',
			tabcurrent: 'var(--tabcurrent)',
			tabtext: 'var(--tabtext)',
			tabcurrenttext: 'var(--tabcurrenttext)',
			tabtexthover: 'var(--tabtexthover)',
			rosterbutton: 'var(--rosterbutton)',
		},
	},
	variants: {
		extend: {
			// backgroundColor: ['active'],
			// textColor: ['active'],
		},
	},
	plugins: [],
};
